kind: CSIVXFlexOS
apiVersion: storage.dell.com/v1
metadata:
  name: powerflex
  namespace: powerflex
spec:
  driver:
    common:
      envs:
        - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
          value: 'true'
        - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
          value: 'true'
        - name: X_CSI_DEBUG
          value: 'true'
        - name: X_CSI_ALLOW_RWO_MULTI_POD_ACCESS
          value: 'true'
      image: >-
        docker.io/dellemc/csi-vxflexos@sha256:dc7dd77ac48d7e54a52b47398fa995ea28331eec1459d7da95cc4c0cf390556c
      imagePullPolicy: IfNotPresent
    tlsCertSecret: vxflexos-certs
    configVersion: v2.4.0
    authSecret: vxflexos-creds
    controller:
      envs: null
      nodeSelector: null
      tolerations: null
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: File
    initContainers:
      - envs:
          - name: MDM
            value: '10.0.0.77,10.0.0.30'
        image: >-
          docker.io/dellemc/sdc@sha256:e5f471d966576b7ed88310bf5d9b784edfaa29af334ab471b22d26a07ad08ac0
        imagePullPolicy: IfNotPresent
        name: sdc
    node:
      envs: null
      nodeSelector: null
      tolerations: null
    replicas: 1
    sideCars:
      - envs:
          - name: HOST_PID
            value: '1'
          - name: MDM
            value: '10.0.0.77,10.0.0.30'
        name: sdc-monitor
