kind: CSIVXFlexOS
apiVersion: storage.dell.com/v1
metadata:
  name: powerflex
  namespace: powerflex
spec:
  driver:
    common:
      envs:
        - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
          value: 'true'
        - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
          value: 'true'
        - name: X_CSI_DEBUG
          value: 'true'
        - name: X_CSI_ALLOW_RWO_MULTI_POD_ACCESS
          value: 'true'
      image: >-
        docker.io/dellemc/csi-vxflexos@sha256:dc7dd77ac48d7e54a52b47398fa995ea28331eec1459d7da95cc4c0cf390556c
      imagePullPolicy: IfNotPresent
    configVersion: v2.4.0
    controller:
      envs: null
      nodeSelector: null
      tolerations: null
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: File
    initContainers:
      - envs:
          - name: MDM
            value: '192.168.112.51,192.168.112.52,192.168.112.53,10.0.0.77,10.0.0.30,10.0.0.154'
        image: >-
          docker.io/dellemc/sdc@sha256:784b3ad7c0d5fbea8267e7e0be1830383f31d6bb57e4626c55cf5d0de344a272
        imagePullPolicy: IfNotPresent
        name: sdc
    node:
      envs: null
      nodeSelector: null
      tolerations: null
    replicas: 1
    sideCars:
      - envs:
          - name: HOST_PID
            value: '1'
          - name: MDM
            value: '192.168.112.51,192.168.112.52,192.168.112.53,10.0.0.77,10.0.0.30,10.0.0.154'
        name: sdc-monitor
