---
version: v2.10.1

images:
  driver: dellemc/csi-vxflexos:v2.10.1
  powerflexSdc: dellemc/sdc:4.5.1
  attacher: registry.k8s.io/sig-storage/csi-attacher:v4.5.0
  provisioner: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
  snapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v7.0.1
  resizer: registry.k8s.io/sig-storage/csi-resizer:v1.10.0
  registrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
  healthmonitor: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.11.0
  replication: dellemc/dell-csi-replicator:v1.8.1
  vgsnapshotter: dellemc/csi-volumegroup-snapshotter:v1.5.0
  podmon: dellemc/podmon:v1.9.1
  authorization: dellemc/csm-authorization-sidecar:v1.10.1

certSecretCount: 0
logLevel: "debug"
logFormat: "TEXT"
kubeletConfigDir: /var/lib/kubelet
defaultFsType: ext4
imagePullPolicy: IfNotPresent
externalAccess:
enableQuota: false
enablesnapshotcgdelete: "false"
enablelistvolumesnapshot: "false"
allowRWOMultiPodAccess: "false"
fsGroupPolicy: File
maxVxflexosVolumesPerNode: 0
  replication:
    enabled: false
    replicationContextPrefix: "powerflex"
    replicationPrefix: "replication.storage.dell.com"

  healthMonitor:
    enabled: false
    interval: 60s
  volumeNamePrefix: k8s
  controllerCount: 2

  snapshot:
    enabled: true

  resizer:
    enabled: true
  nodeSelector:
  tolerations:
node:
  healthMonitor:
    enabled: false
  nodeSelector:
  tolerations:
  renameSDC:
    enabled: false
    prefix: "sdc-test"
  approveSDC: 
    enabled: false
storageCapacity:
  enabled: true
  pollInterval: 5m     
monitor:
  enabled: false
  hostNetwork: true
  hostPID: true

vgsnapshotter:
  enabled: false
podmon:
  enabled: false

  controller:
    args:
      - "--csisock=unix:/var/run/csi/csi.sock"
      - "--labelvalue=csi-vxflexos"
      - "--mode=controller"
      - "--skipArrayConnectionValidation=false"
      - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
      - "--driverPodLabelValue=dell-storage"
      - "--ignoreVolumelessPods=false"
  node:
    args:
      - "--csisock=unix:/var/lib/kubelet/plugins/vxflexos.emc.dell.com/csi_sock"
      - "--labelvalue=csi-vxflexos"
      - "--mode=node"
      - "--leaderelection=false"
      - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
      - "--driverPodLabelValue=dell-storage"
      - "--ignoreVolumelessPods=false"

authorization:
  enabled: false
  proxyHost:
  skipCertificateValidation: true
